### ISSUE TITLE
Add me as a contributor  

### ISSUE THREAD

**Issue by BaileyJM02** [voximity/qubit#23]
This is a **MAJOR** bug. Can you add me as a contributor through settings? Cheers. :D

**Comment by miwilc** [comment]
Lol what.

**Comment by miwilc** [comment]
GitHub does that automatically anyway~

**Comment by BaileyJM02** [comment]
I mean as moderator access   
  
  
  
  
  
  
  
  
  
  
  
BAILEY MATTHEWS
  
  Web Developer
  
Website: Bailey.guru
  
  Email: Bailey@Bailey.guru
  
  
  

  

  

  

  

This message contains confidential information and is intended only for the intended recipients. If you are not an intended recipient you should not disseminate, distribute or copy this e-mail. Please notify us immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. Therefore we do not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

  
  
  
  
  
  
  

  
  
>

**Comment by miwilc** [comment]
... disable your signature for GitHub. All replies are public.


Moderators are not required as yet. It's not a actual project.

**Comment by voximity** [comment]
No
